### ISSUE TITLE
Error downloading qt5.9.7 when trying to install/make certain stages

### ISSUE THREAD

**Issue by hhollandmoritz** [epruesse/ymp#89] opened 2019-06-20 22:49 UTC
Thanks for your patience with my issues today. I have tried to install/make several stages and keep getting a failure on qt-5.9.7 the download/installation step.  For example 

```ymp env install multiqc``` 

results in

```
YMP Creating 1 environments.
YMP Creating environment 'multiqc'
YMP Downloading 76 files.
YMP Download skipped: ca-certificates-2019.3.9-hecc5488_0.tar.bz2 (file exists, md5 verified)                                                                                           
YMP Download skipped: libgcc-ng-8.2.0-hdf63c60_1.tar.bz2 (file exists, md5 verified)        
YMP Download skipped: libgfortran-ng-7.3.0-hdf63c60_0.tar.bz2 (file exists, md5 verified)   
YMP Download skipped: libstdcxx-ng-8.2.0-hdf63c60_1.tar.bz2 (file exists, md5 verified)     
YMP Download skipped: expat-2.2.5-hf484d3e_1002.tar.bz2 (file exists, md5 verified)         
YMP Download skipped: icu-58.2-hf484d3e_1000.tar.bz2 (file exists, md5 verified)            
YMP Download skipped: jpeg-9c-h14c3975_1001.tar.bz2 (file exists, md5 verified)             
YMP Download skipped: libffi-3.2.1-he1b5a44_1006.tar.bz2 (file exists, md5 verified)        
YMP Download skipped: libiconv-1.15-h516909a_1005.tar.bz2 (file exists, md5 verified)       
YMP Download skipped: libuuid-2.32.1-h14c3975_1000.tar.bz2 (file exists, md5 verified)      
YMP Download skipped: ncurses-6.1-hf484d3e_1002.tar.bz2 (file exists, md5 verified)         
YMP Download skipped: openblas-0.3.6-h6e990d7_2.tar.bz2 (file exists, md5 verified)         
YMP Download skipped: openssl-1.1.1b-h14c3975_1.tar.bz2 (file exists, md5 verified)         
YMP Download skipped: pcre-8.41-hf484d3e_1003.tar.bz2 (file exists, md5 verified)           
YMP Download skipped: pthread-stubs-0.4-h14c3975_1001.tar.bz2 (file exists, md5 verified)   
YMP Download skipped: xorg-libxau-1.0.9-h14c3975_0.tar.bz2 (file exists, md5 verified)      
YMP Download skipped: xorg-libxdmcp-1.1.3-h516909a_0.tar.bz2 (file exists, md5 verified)    
YMP Download skipped: xz-5.2.4-h14c3975_1001.tar.bz2 (file exists, md5 verified)            
YMP Download skipped: yaml-0.1.7-h14c3975_1001.tar.bz2 (file exists, md5 verified)          
YMP Download skipped: zlib-1.2.11-h14c3975_1004.tar.bz2 (file exists, md5 verified)         
YMP Download skipped: gettext-0.19.8.1-hc5be6a0_1002.tar.bz2 (file exists, md5 verified)    
YMP Download skipped: libblas-3.8.0-9_openblas.tar.bz2 (file exists, md5 verified)          
YMP Download skipped: libpng-1.6.37-hed695b0_0.tar.bz2 (file exists, md5 verified)          
YMP Download skipped: libxcb-1.13-h14c3975_1002.tar.bz2 (file exists, md5 verified)         
YMP Download skipped: libxml2-2.9.9-h13577e0_0.tar.bz2 (file exists, md5 verified)          
YMP Download skipped: readline-7.0-hf8c457e_1001.tar.bz2 (file exists, md5 verified)        
YMP Download skipped: tk-8.6.9-h84994c4_1001.tar.bz2 (file exists, md5 verified)            
YMP Download skipped: freetype-2.10.0-he983fc9_0.tar.bz2 (file exists, md5 verified)        
YMP Download skipped: glib-2.58.3-hf63aee3_1001.tar.bz2 (file exists, md5 verified)         
YMP Download skipped: libcblas-3.8.0-9_openblas.tar.bz2 (file exists, md5 verified)         
YMP Download skipped: liblapack-3.8.0-9_openblas.tar.bz2 (file exists, md5 verified)        
YMP Download skipped: sqlite-3.26.0-h67949de_1001.tar.bz2 (file exists, md5 verified)       
YMP Download skipped: dbus-1.13.6-he372182_0.tar.bz2 (file exists, md5 verified)            
YMP Download skipped: fontconfig-2.13.1-he4413a7_1000.tar.bz2 (file exists, md5 verified)   
YMP Download skipped: gstreamer-1.14.4-h66beb1c_1001.tar.bz2 (file exists, md5 verified)    
YMP Download skipped: python-3.6.7-h381d211_1004.tar.bz2 (file exists, md5 verified)        
YMP Download skipped: asn1crypto-0.24.0-py36_1003.tar.bz2 (file exists, md5 verified)       
YMP Download skipped: certifi-2019.3.9-py36_0.tar.bz2 (file exists, md5 verified)           
YMP Download skipped: chardet-3.0.4-py36_1003.tar.bz2 (file exists, md5 verified)           
YMP Download skipped: click-7.0-py_0.tar.bz2 (file exists, md5 verified)                    
YMP Download skipped: decorator-4.4.0-py_0.tar.bz2 (file exists, md5 verified)              
YMP Download skipped: future-0.17.1-py36_1000.tar.bz2 (file exists, md5 verified)           
YMP Download skipped: gst-plugins-base-1.14.4-hdf3bae2_1001.tar.bz2 (file exists, md5 verified)                                                                                         
YMP Download skipped: idna-2.8-py36_1000.tar.bz2 (file exists, md5 verified)                
YMP Download skipped: kiwisolver-1.1.0-py36hc9558a2_0.tar.bz2 (file exists, md5 verified)   
YMP Download skipped: markdown-2.6.11-py_0.tar.bz2 (file exists, md5 verified)              
YMP Download skipped: markupsafe-1.1.1-py36h14c3975_0.tar.bz2 (file exists, md5 verified)   
YMP Download skipped: numpy-1.16.3-py36he5ce36f_0.tar.bz2 (file exists, md5 verified)       
YMP Download skipped: pycparser-2.19-py36_1.tar.bz2 (file exists, md5 verified)             
YMP Download skipped: pyparsing-2.4.0-py_0.tar.bz2 (file exists, md5 verified)              
YMP Download skipped: pysocks-1.7.0-py36_0.tar.bz2 (file exists, md5 verified)              
YMP Download skipped: pyyaml-5.1-py36h14c3975_0.tar.bz2 (file exists, md5 verified)         
YMP Download skipped: simplejson-3.16.1-py36h470a237_0.tar.bz2 (file exists, md5 verified)  
YMP Download skipped: sip-4.19.8-py36hf484d3e_1000.tar.bz2 (file exists, md5 verified)      
YMP Download skipped: six-1.12.0-py36_1000.tar.bz2 (file exists, md5 verified)              
YMP Download skipped: tornado-6.0.2-py36h516909a_0.tar.bz2 (file exists, md5 verified)      
YMP Download skipped: cffi-1.12.3-py36h8022711_0.tar.bz2 (file exists, md5 verified)        
YMP Download skipped: cycler-0.10.0-py_1.tar.bz2 (file exists, md5 verified)                
YMP Download skipped: lzstring-1.0.4-py_1001.tar.bz2 (file exists, md5 verified)            
YMP Download skipped: python-dateutil-2.8.0-py_0.tar.bz2 (file exists, md5 verified)        
YMP Download skipped: setuptools-41.0.1-py36_0.tar.bz2 (file exists, md5 verified)          
YMP Download skipped: cryptography-2.6.1-py36h72c5cf5_0.tar.bz2 (file exists, md5 verified) 
YMP Download skipped: jinja2-2.10.1-py_0.tar.bz2 (file exists, md5 verified)                
YMP Download skipped: matplotlib-base-3.0.3-py36h5f35d83_1.tar.bz2 (file exists, md5 verified)                                                                                          
YMP Download skipped: networkx-2.0-py36_1.tar.bz2 (file exists, md5 verified)               
YMP Download skipped: pyqt-5.9.2-py36hcca6a23_0.tar.bz2 (file exists, md5 verified)         
YMP Download skipped: wheel-0.33.4-py36_0.tar.bz2 (file exists, md5 verified)               
YMP Download skipped: colormath-3.0.0-py_2.tar.bz2 (file exists, md5 verified)              
YMP Download skipped: matplotlib-3.0.3-py36_1.tar.bz2 (file exists, md5 verified)           
YMP Download skipped: pip-19.1-py36_0.tar.bz2 (file exists, md5 verified)                   
YMP Download skipped: pyopenssl-19.0.0-py36_0.tar.bz2 (file exists, md5 verified)           
YMP Download skipped: spectra-0.0.11-py_0.tar.bz2 (file exists, md5 verified)               
YMP Download skipped: urllib3-1.24.2-py36_0.tar.bz2 (file exists, md5 verified)             
YMP Download skipped: requests-2.21.0-py36_1000.tar.bz2 (file exists, md5 verified)         
YMP Download skipped: multiqc-1.7-py_4.tar.bz2 (file exists, md5 verified)                  
YMP Download failed: qt-5.9.7-h52cfd70_1.tar.bz2 (error code 404)                           
YMP   URL: 'https://conda.anaconda.org/conda-forge/linux-64/qt-5.9.7-h52cfd70_1.tar.bz2#e84212949147e139484cd8f0ea68f8ba'                                                               
YMP Download failed: qt-5.9.7-h52cfd70_1.tar.bz2 (error code 404)                           
YMP   URL: 'https://conda.anaconda.org/conda-forge/linux-64/qt-5.9.7-h52cfd70_1.tar.bz2#e84212949147e139484cd8f0ea68f8ba'                                                               
YMP Overwriting: qt-5.9.7-h52cfd70_1.tar.bz2 (md5 failed)                                   
YMP Download failed: qt-5.9.7-h52cfd70_1.tar.bz2 (md5 failed)                               
YMP Download failed: qt-5.9.7-h52cfd70_1.tar.bz2 (error code 404)                           
YMP   URL: 'https://conda.anaconda.org/conda-forge/label/cf201901/linux-64/qt-5.9.7-h52cfd70_1.tar.bz2#e84212949147e139484cd8f0ea68f8ba'                                                
YMP Download failed: qt-5.9.7-h52cfd70_1.tar.bz2 (error code 404)                           
YMP   URL: 'https://conda.anaconda.org/conda-forge/label/old_feature_broken/linux-64/qt-5.9.7-h52cfd70_1.tar.bz2#e84212949147e139484cd8f0ea68f8ba'                                      
YMP Finished downloads.                                                                     
Error: Unable to create environment multiqc, because downloads failed. See log for details.s
```
It looks like the download link is broken for some reason. I was able to force conda to install multiqc (qt-5.9.7 and all) in a separate (non-ymp environment) so I think the issue lies somewhere in the ymp-specific configuration. Is there a way to guide to ymp to a working link for qt-5.9.7? 

Thanks!

**Comment by epruesse** [comment] 2019-06-21 01:22
Argh - another one. You don't know how much effort has gone into this to make installing the envs safe and sane.

If this happens, you can force an environment to install "from scratch" using the conda solver:

```
ymp env install -e '' multiqc
```

The command asks ymp to call conda to install the named environments. The `-e`  flag tells it which set of precomputed env specs to use. Setting that to an empty string means ymp has to have the env solved from scratch.

The catch is that those won't have run through tests online. But if it won't install it won't install. Looks like the qt package has either changed or was moved or deleted. Happens occasionally, unfortunately. :(

BTW: You can use

```
ymp env run multiqc -- multiqc --help
```

to run stuff in the env. Including `ymp env run multiqc bash` to get a shell in there or `ymp env run multiqc conda install whatever` to alter the env. It's just a conda env after all. The `--` in the call above is to tell ymp everything behind is the command and to ignore the `--help` (same thing works for grep or rm if you need to act on things beginning with a dash).

**Comment by epruesse** [comment] 2019-06-21 01:27
So yes, `https://conda.anaconda.org/conda-forge/linux-64/qt-5.9.7-h52cfd70_1.tar.bz2` was moved to `https://conda.anaconda.org/conda-forge/label/broken/linux-64/qt-5.9.7-h52cfd70_1.tar.bz2`. Need to check why YMP didn't check that. In theory, it should try the `broken` label.

**Comment by epruesse** [comment] 2019-06-21 01:53
Ok... so the file hasn't just moved, it also changed contents. That's why YMP is refusing to install the env. Well... that's what it was designed to do. I need to put a help message there to use `ymp env install -e xyz`.

**Comment by epruesse** [comment] 2020-07-18 17:45
Hopefully, this has been fixed in the mean time.

**Closed by epruesse** 2020-07-18 17:45 UTC
